Repository echo-swent/echo, pull requests merged in 2024-05, with the labels that each got.

#183 HamburgerMenuDrawerSheet : Removing the unnecessary stuff
  app/src/main/java/com/github/swent/echo/compose/components/HamburgerMenuDrawerSheet.kt
Labels: enhancement

#203 🐛 FIX: max participant and inscription counts were inversed
  app/src/main/java/com/github/swent/echo/data/supabase/entities/EventSupabase.kt
  app/src/main/java/com/github/swent/echo/data/supabase/entities/EventSupabaseSetter.kt
  app/src/test/java/com/github/swent/echo/data/supabase/entities/EventSupabaseSetterTest.kt
  app/src/test/java/com/github/swent/echo/data/supabase/entities/EventSupabaseTest.kt
Labels: bug

#188 New view model (latest one)
  app/src/androidTest/java/com/github/swent/echo/compose/authentication/CreateProfileTest.kt
  app/src/main/java/com/github/swent/echo/compose/authentication/CreateProfile.kt
  app/src/main/java/com/github/swent/echo/compose/navigation/AppNavigationHost.kt
  app/src/main/java/com/github/swent/echo/ui/navigation/Navigation.kt
  app/src/main/java/com/github/swent/echo/viewmodels/authentication/CreateProfileViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/swent/echo/viewmodels/authentication/CreateProfileViewModelTest.kt
Labels: enhancement

#251 Create the logic for the associations in the app
  docs/integration-association.md
Labels: documentation

#279 search mode interactions with UI
  app/src/main/java/com/github/swent/echo/compose/components/HomeScreen.kt
  app/src/main/java/com/github/swent/echo/compose/components/TopAppBar.kt
  app/src/main/java/com/github/swent/echo/viewmodels/HomeScreenViewModel.kt
  app/src/main/res/drawable/search_off.xml
Labels: enhancement

#289 Fix app crash when register with an existing account
  app/src/main/java/com/github/swent/echo/viewmodels/authentication/AbstractAuthenticationViewModel.kt
Labels: bug

#309 Prevent the Map from requesting location more than once.
  app/src/main/java/com/github/swent/echo/compose/components/HomeScreen.kt
  app/src/main/java/com/github/swent/echo/compose/map/Map.kt
  app/src/main/java/com/github/swent/echo/compose/navigation/AppNavigationHost.kt
Labels: bug

#319 m3 board
  docs/EchoM3Board.tsv
Labels: documentation

#322 add user stories
  docs/EchoM3Board.tsv
Labels: documentation

#367 Fix app crash when switching theme
  app/src/main/java/com/github/swent/echo/compose/map/MapLibreMapViewProvider.kt
Labels: bug
