Repository echo-swent/echo, pull requests merged in 2024-04, with the labels that each got.

#47 Add architecture diagram to the README
  README.md
  architecture.png
Labels: documentation

#80 Modify the `Event` data class.
  app/src/androidTest/java/com/github/swent/echo/compose/components/EventInfoSheetTest.kt
  app/src/androidTest/java/com/github/swent/echo/compose/components/HomeScreenTest.kt
  app/src/androidTest/java/com/github/swent/echo/compose/map/MapViewAndroidTest.kt
  app/src/androidTest/java/com/github/swent/echo/data/repository/datasources/SupabaseTest.kt
  app/src/main/java/com/github/swent/echo/compose/components/EventInfoSheet.kt
  app/src/main/java/com/github/swent/echo/compose/components/HomeScreen.kt
  app/src/main/java/com/github/swent/echo/data/model/Event.kt
  app/src/main/java/com/github/swent/echo/viewmodels/event/EventViewModel.kt
  app/src/test/java/com/github/swent/echo/data/repository/RepositoryImplTest.kt
  app/src/test/java/com/github/swent/echo/viewmodels/event/EventViewModelTest.kt
Labels: enhancement, help wanted

#77 created the docs folder and moved files into it
  README.md
  docs/DB_Structure.md
  docs/architecture.png
Labels: documentation

#137 Move all compose tests (which work with robolectric) to the test folder
  app/src/test/java/com/github/swent/echo/compose/components/EventInfoSheetTest.kt
  app/src/test/java/com/github/swent/echo/compose/components/MainScreenTagsTest.kt
  app/src/test/java/com/github/swent/echo/compose/components/SearchButtonTest.kt
  app/src/test/java/com/github/swent/echo/compose/components/SearchMenuSheetTest.kt
  app/src/test/java/com/github/swent/echo/compose/components/searchmenu/SearchMenuFiltersTest.kt
  app/src/test/java/com/github/swent/echo/compose/event/CreateEventScreenTest.kt
Labels: enhancement

#154 Delete existing markers when the list of events is updated.
  app/src/main/java/com/github/swent/echo/compose/map/MapLibreMapViewProvider.kt
Labels: bug

#170 Always use the `SimpleRepository` in android tests.
  app/src/androidTest/java/com/github/swent/echo/di/FakeRepositoryModule.kt
Labels: enhancement
